version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgres:15.2"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "8080:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
  frontend:
    build: ./frontend/jellyfish-cups
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/jellyfish-cups:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env

volumes:
  postgres_data:
  pgadmin_data:
